name: Test

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run asMSX
        uses: docker://ghcr.io/duhow/asMSX:master
        with:
          args: GAME.ASM
      - name: Check content
        run: ls -la
